version: '3'

services:
  gas_app:
    init: true
    container_name: gas_app
    ports:
      - "80:80"
    environment:
      - "DEBUG=True"
      - "SECRET_KEY=xxxxxx"
      - "ALLOWED_HOSTS=*"
    build: 
      context: .
      target: base
    volumes:
      - .:/app
