version: '3'

services:
  gas_db:
    container_name: gas_db
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
  gas_app:
    container_name: gas_app
    command: python manage.py runserver 0.0.0.0:80
    #command: django-admin.py startproject gasapp .
    ports:
      - "80:80"
    environment:
      - "DJANGO_DEBUG=True"
    build: 
      context: .      
    volumes:
      - .:/code
    depends_on:
      - gas_db
