version: '3'

services:
  gas_app:
    container_name: gas_app
    ports:
      - "80:80"
    environment:
      - "DEBUG=True"
      - "SECRET_KEY=xxxxxx"
    build: 
      context: .      
    volumes:
      - .:/code
