version: '3'

services:
  gas_app:
    init: true
    container_name: gas_app
    ports:
      - "2080:80"
    environment:
      - "DEBUG=True"
      - "SECRET_KEY=xxxxxx"
      - "ALLOWED_HOSTS=*"
      - "SENTRY_DSN=https://public@sentry.example.com/1"
    build: 
      context: .
    volumes:
      - .:/app
