services:
  gas_app:
    init: true
    container_name: gas_app
    ports:
      - "8080:8080"
    build:
      context: .
    volumes:
      - ./static:/app/static:ro
      - ./gasapp/templates:/app/gasapp/templates:ro
