# Generated by Django 2.2.5 on 2019-09-23 21:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('postal_code', models.CharField(max_length=8, verbose_name='postal code')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('opening_hours', models.CharField(max_length=200, verbose_name='opening hours')),
                ('town', models.CharField(max_length=200, verbose_name='town')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('gasoil', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='gasoil')),
                ('petrol95', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='gasolina 95')),
                ('petrol98', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='gasolina 98')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
            },
        ),
    ]
