# Generated by Django 2.2.5 on 2019-09-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'station', 'verbose_name_plural': 'stations'},
        ),
    ]
