name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps: 
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only --build-arg BUILD_VERSION=$(date +'%Y%m%d%H%M%S').${{ github.ref_name }}.$(git rev-parse --short HEAD) --build-arg GIT_REV=${{ github.sha }}
